import React from 'react'

function Home() {
    return (
        <div className="max-w-4xl  p-2 m-1 border mt-20">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem ipsam neque nemo ipsum dolore laborum tenetur odit commodi, facilis similique nostrum voluptas nesciunt dolorum, nisi est cumque provident sapiente omnis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            ipsum dolor sit amet consectetur adipisicing elit. Voluptatem ipsam neque nemo ipsum dolore laborum tenetur odit commodi, facilis similique nostrum voluptas nesciunt dolorum, nisi est cumque provident sapiente omnis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            ipsum dolor sit amet consectetur adipisicing elit. Voluptatem ipsam neque nemo ipsum dolore laborum tenetur odit commodi, facilis similique nostrum voluptas nesciunt dolorum, nisi est cumque provident sapiente omnis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            ipsum dolor sit amet consectetur adipisicing elit. Voluptatem ipsam neque nemo ipsum dolore laborum tenetur odit commodi, facilis similique nostrum voluptas nesciunt dolorum, nisi est cumque provident sapiente omnis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores praesentium provident minus in quod excepturi ex ratione, quaerat voluptas, aut optio saepe assumenda illo temporibus. Odio earum exercitationem minima?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto necessitatibus facilis enim odit autem doloribus nisi voluptatum, aliquid, suscipit soluta inve
        </div>)
}

export default Home